### PR TITLE
feat: add pagination clients support

### PR DESCRIPTION
**Pull request by DavideSegullo**
This PR exposes both in the JS and Python client the parameters to be able to use pagination

### CODE REVIEW

**Review by rosepuppy — COMMENTED** [review]
Change lgtm! We require the v4-client-js npm version to be bumped manually for the change to be reflected, so just need to bump the version.

**Comment by DavideSegullo** [comment]
> Change lgtm! We require the v4-client-js npm version to be bumped manually for the change to be reflected, so just need to bump the version.

Done!

**Comment by rosepuppy** [comment]
@DavideSegullo not sure why the python tests are failing. I don't think we are maintaining the python client anymore. I think you can remove those changes if you don't need it for now.

**Review by rosepuppy — APPROVED** [review]

**Comment by DavideSegullo** [comment]
> @DavideSegullo not sure why the python tests are failing. I don't think we are maintaining the python client anymore. I think you can remove those changes if you don't need it for now.

Yep, I'll revert it

**Comment by DavideSegullo** [comment]
@rosepuppy Done!

**Pull request merged**
